
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author randel
 */
public class Urna_interface extends javax.swing.JFrame {      
    ArrayList<JButton> botoes = new ArrayList<>(13);    
    
    public Urna_interface() {
        initComponents();
        add_botoes();
        invisivel_botoes(botoes);           
        jLabel5.setBorder(null);  
        
    }
    
    public void invisivel_botoes(ArrayList<JButton> botoes){
        for(JButton botao : botoes){
            botao.setOpaque(false);
            botao.setContentAreaFilled(false);
            botao.setBorderPainted(false);
        }
    }

    public void add_botoes(){
        botoes.add(jButtonn0);
        botoes.add(jButtonn1);
        botoes.add(jButtonn2);
        botoes.add(jButtonn3);
        botoes.add(jButtonn4);
        botoes.add(jButtonn5);
        botoes.add(jButtonn6);
        botoes.add(jButtonn7);
        botoes.add(jButtonn8);
        botoes.add(jButtonn9);
        botoes.add(jButtonBranco);
        botoes.add(jButtonConfirmar);
        botoes.add(jButtonCorrigir);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBranco = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCorrigir = new javax.swing.JButton();
        jButtonn3 = new javax.swing.JButton();
        jButtonn1 = new javax.swing.JButton();
        jButtonn2 = new javax.swing.JButton();
        jButtonn4 = new javax.swing.JButton();
        jButtonn5 = new javax.swing.JButton();
        jButtonn6 = new javax.swing.JButton();
        jButtonn7 = new javax.swing.JButton();
        jButtonn0 = new javax.swing.JButton();
        jButtonn9 = new javax.swing.JButton();
        jButtonn8 = new javax.swing.JButton();
        jLabelN2 = new javax.swing.JLabel();
        jLabelN3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelN1 = new javax.swing.JLabel();
        jLabelN4 = new javax.swing.JLabel();
        jLabelImagemPrincipal = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelBunero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrancoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 110, 60));
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 580, 100, 70));

        jButtonCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrigirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCorrigir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 100, 60));

        jButtonn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 70, 60));

        jButtonn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 70, 60));

        jButtonn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 70, 60));

        jButtonn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 70, 60));

        jButtonn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 70, 60));

        jButtonn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 70, 60));

        jButtonn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 70, 60));

        jButtonn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 70, 60));

        jButtonn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 70, 60));

        jButtonn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 70, 60));

        jLabelN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 40, 40));

        jLabelN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 40, 40));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 40, 40));

        jLabelN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 40, 40));

        jLabelN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 40, 40));
        getContentPane().add(jLabelImagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 160, 170));
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 270, 40));

        jLabelBunero.setText("Número: ");
        getContentPane().add(jLabelBunero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deputado Estadual");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 240, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/randel/Downloads/urna-eletrônicaNew.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 730));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 60, 70));

        setSize(new java.awt.Dimension(1191, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn1ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"1");               
        
        int a = 0;
        while(a < 10){
            jLabelN1.setBorder(new LineBorder(new Color(128,128,128)));        
            jLabelN1.setBorder(new LineBorder(new Color(203,199,199)));        
            jLabelN1.setBorder(new LineBorder(new Color(76,76,76)));        
            a++;
        }
    }//GEN-LAST:event_jButtonn1ActionPerformed

    private void jButtonn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn2ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"2");
    }//GEN-LAST:event_jButtonn2ActionPerformed

    private void jButtonn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn3ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"3");
    }//GEN-LAST:event_jButtonn3ActionPerformed

    private void jButtonn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn4ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"4");
    }//GEN-LAST:event_jButtonn4ActionPerformed

    private void jButtonn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn5ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"5");
    }//GEN-LAST:event_jButtonn5ActionPerformed

    private void jButtonn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn6ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"6");
    }//GEN-LAST:event_jButtonn6ActionPerformed

    private void jButtonn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn7ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"7");
    }//GEN-LAST:event_jButtonn7ActionPerformed

    private void jButtonn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn8ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"8");
    }//GEN-LAST:event_jButtonn8ActionPerformed

    private void jButtonn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn9ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"9");
    }//GEN-LAST:event_jButtonn9ActionPerformed

    private void jButtonn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn0ActionPerformed
        jTextFieldNumero.setText(jTextFieldNumero.getText()+"0");
    }//GEN-LAST:event_jButtonn0ActionPerformed

    private void jButtonBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrancoActionPerformed
        
    }//GEN-LAST:event_jButtonBrancoActionPerformed

    private void jButtonCorrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrigirActionPerformed
        jTextFieldNumero.setText("");
    }//GEN-LAST:event_jButtonCorrigirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBranco;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonCorrigir;
    private javax.swing.JButton jButtonn0;
    private javax.swing.JButton jButtonn1;
    private javax.swing.JButton jButtonn2;
    private javax.swing.JButton jButtonn3;
    private javax.swing.JButton jButtonn4;
    private javax.swing.JButton jButtonn5;
    private javax.swing.JButton jButtonn6;
    private javax.swing.JButton jButtonn7;
    private javax.swing.JButton jButtonn8;
    private javax.swing.JButton jButtonn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBunero;
    private javax.swing.JLabel jLabelImagemPrincipal;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelN2;
    private javax.swing.JLabel jLabelN3;
    private javax.swing.JLabel jLabelN4;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
